# Generated by Django 5.1.7 on 2025-04-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
