# Generated by Django 5.1.7 on 2025-04-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_customer_color_customer_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whatsapp.company'),
        ),
    ]
