# Generated by Django 5.1.7 on 2025-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_alter_clientdata_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_host_user',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
